version: 0.2

phases:
  pre_build:
    commands:
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

  build:
    commands:
      - docker build . -t $IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"Nginx-Forgate-Dockerhubnew","imageUri":"artemtabolich/nginx-task14","portMappings":[{"containerPort":80,"hostPort":80}],"essential":true}]' > imagedefinitions.json
      - printf '[{"name":"Apache2-Forgate","imageUri":"artemtabolich/apache2-task14","portMappings":[{"containerPort":8888,"hostPort":8888}],"essential":true}]' > imagedefinitions_apache.json
artifacts:
  files:
    - imagedefinitions.json
    - imagedefinitions_apache.json
#DOCKERHUB_USERNAME artemtabolich
#DOCKERHUB_PASSWORD
#IMAGE_REPO_NAME artemtabolich/nginx-task14
#IMAGE_TAG latest
