version: '3'
services:
  apache2:
    image: artemtabolich/apache2-task14
    ports:
      - 8888:8888
    networks:
      - mynetwork

  nginx:
    image: artemtabolich/nginx-task14
    ports:
      - 80:80
    networks:
      - mynetwork

networks:
  mynetwork:


